name: Dynamic CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "main"

      program_file:
        description: "Program File"
        required: true
        default: "app.py"

      test_file:
        description: "Test File"
        required: true
        default: "test_app.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest

      - name: Run program file
        run: python ${{ github.event.inputs.program_file }}

      - name: Run selected test file
        run: pytest ${{ github.event.inputs.test_file }} -v
